{{- if and (or (not (hasKey .Values.ui "enabled")) (.Values.ui.enabled)) .Values.ui.gateway.enabled .Values.ui.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "dwpk.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: ui
  name: {{ include "dwpk.resourceName" (dict "suffix" "ui-gateway" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ required "ui.gateway.className is required when ui.gateway.create is true" .Values.ui.gateway.className }}
  listeners:
    {{- toYaml .Values.ui.gateway.listeners | nindent 4 }}
{{- end }}
