apiVersion: v2
name: dwpk
description: A Helm chart to deploy dwpk, a development workspace platform for Kubernetes
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/devops-ia/helm-dwpk
  - https://github.com/devops-ia/dwpk
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/devops-ia/dwpk
keywords:
  - kubernetes
  - operator
  - development
  - workspace
  - ssh
  - devcontainer
annotations:
  kubebuilder.io/generated-by: kubebuilder
